#ifndef COMSTACK_CFG_H_
#define COMSTACK_CFG_H_

/*Because many of the communication stack type are depending on the appropriate ECU
 this file shall be generated dependent on the specific ECU configuration for 
 each ECU independently.
 
 *ComStack_Cfg.h shall be generated by the generator to generate the type definition 
 of the PduIdType and PduLengthType from the EcuC Virtual Layer based on the configuration 
 e.g. typedef uint8 PduIdType if number of PDUs are less than 256. 

 *The value of PduIdType and PduLengthType shall be derived from the ‘PduIdTypeEnum’ and 
 ‘PduLengthTypeEnum’ of the EcuCPduCollection container respectively.
 
 *define a label that refere to the max of the variable which should be genrated
 by the tool to use ECU configuration, we then use this defined label we define the type
 in ComStack_Types.h 
 */

/*PduIdType*/
//PduIdmax, the maximum number of a PduId range
#define PduIdmax	PduIdmax_uint8		//the Max number of PDU Id's <256 => PduIdmax_uint8
										//the Max number of PDU Id's >256 => PduIdmax_uint16

/******************************/
/*PduLengthType*/	
//is the length of the largest (possibly segmented) PDU to be sent by the ECU.
#define PduLengthmax  PduLengthmax_unit8
//the Max length for PDU Id's <256 => PduLengthmax_unit8
//the Max length for PDU Id's >256 &&<65536 => PduLengthmax_unit16					
//the Max length for PDU Id's >65536 => PduLengthmax_unit32					
/******************************/

#endif
